# ProfileIt.io configuration file. For help, see https://profileit.io/help.
# Place at RAILS_ROOT/config/profile_it.yml.
common: &defaults
  key: 8cvNC5dyN8kyySTsbIGZ
  profile: true
  name: Fitness

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
